import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowUpRight, Check, Eye, EyeOff, ExternalLink, ScanSearch, Settings, ShieldCheck, Sparkles } from 'lucide-react';
import type { Detection, ScanResult } from '../shared/types';
import { DEMO_RESULT } from '../shared/types';
import { detect, score } from '../detection/engine';
import type { PageSnapshot } from '../shared/types';
import './styles.css';

declare const chrome: any;
export type View = 'popup' | 'sidepanel' | 'options';
const severityClass=(s:string)=>s.toLowerCase();
function riskLabel(n:number){return n<=20?'Low':n<=40?'Mild':n<=60?'Moderate':n<=80?'High':'Very High';}
function Card({d,onShow}:{d:Detection;onShow?:()=>void}){return <article className="d-card"><div className="d-top"><span className={`badge ${severityClass(d.severity)}`}><AlertTriangle size={13}/>{d.pattern}</span><span className="confidence">{d.confidence}% confidence</span></div><blockquote>“{d.evidence}”</blockquote><div className="why"><b>Why this matters</b><p>{d.why}</p></div>{onShow&&d.selector&&<button className="text-btn" onClick={onShow}><Eye size={14}/> Show on page <ArrowUpRight size={13}/></button>}</article>}
function Header({compact=false}:{compact?:boolean}){return <header className="brand"><div className="brand-mark"><ScanSearch size={19}/></div><div><strong>DarkLens</strong>{!compact&&<span>See what websites are trying to make you do.</span>}</div></header>}
async function activeTab(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});return tabs[0];}
async function scanCurrent():Promise<ScanResult>{const tab=await activeTab(); const host=new URL(tab.url || 'https://unknown').hostname || 'this page'; let snapshot:PageSnapshot; try{snapshot=await chrome.tabs.sendMessage(tab.id,{type:'extract'});}catch{snapshot={title:tab.title||'',text:'',buttons:[],timers:[],checkboxes:[],prices:[]};} const detections=detect(snapshot); const result={url:tab.url||'',hostname:host,title:snapshot.title||tab.title||'',detections,score:score(detections),scannedAt:Date.now()}; await chrome.storage.local.set({lastResult:result}); return result;}
export function App({view}:{view:View}){const [result,setResult]=useState<ScanResult|null>(null);const [loading,setLoading]=useState(false);const [highlight,setHighlight]=useState(true);const [settings,setSettings]=useState({auto:false,highlight:true,ai:false,analyzeForms:false,history:false});
 useEffect(()=>{chrome.storage.local.get(['lastResult','settings']).then((x:any)=>{if(x.lastResult)setResult(x.lastResult);if(x.settings){setSettings(x.settings);setHighlight(x.settings.highlight!==false);}})},[]);
 const run=async()=>{setLoading(true);try{setResult(await scanCurrent())}finally{setLoading(false)}};
 const demo=()=>{setResult(DEMO_RESULT);chrome.storage.local.set({lastResult:DEMO_RESULT});};
 const show=(d:Detection)=>{if(!highlight||!d.selector)return;activeTab().then(t=>chrome.tabs.sendMessage(t.id,{type:'highlight',selector:d.selector}));};
 const openPanel=()=>chrome.runtime.sendMessage({type:'open-sidepanel'});
 const saveSettings=(next:any)=>{setSettings(next);chrome.storage.local.set({settings:next});setHighlight(next.highlight);};
 if(view==='options')return <main className="options-page"><Header/><section className="settings-wrap"><div className="eyebrow">CONTROL CENTER</div><h1>Settings</h1><p className="muted">Keep analysis local, transparent, and under your control.</p><Setting title="Scan automatically" desc="Analyze pages when they finish loading." value={settings.auto} onChange={v=>saveSettings({...settings,auto:v})}/><Setting title="Highlight detected elements" desc="Outline evidence directly on the page." value={settings.highlight} onChange={v=>saveSettings({...settings,highlight:v})}/><div className="section-label">OPTIONAL AI</div><Setting title="AI enabled" desc="Reserved for a provider you configure. Rule-based analysis works without it." value={settings.ai} onChange={v=>saveSettings({...settings,ai:v})}/><label className="field">Provider<input placeholder="No provider configured" disabled/></label><label className="field">API key<input type="password" placeholder="Stored locally when configured" disabled/></label><div className="section-label">PRIVACY</div><Setting title="Analyze forms" desc="Off by default. Sensitive field values are never collected." value={settings.analyzeForms} onChange={v=>saveSettings({...settings,analyzeForms:v})}/><Setting title="Store scan history" desc="Off by default. Last result is kept only for this extension session." value={settings.history} onChange={v=>saveSettings({...settings,history:v})}/><div className="privacy-note"><ShieldCheck size={18}/><span>DarkLens excludes passwords, payment fields, contenteditable fields, and private form input from extraction.</span></div></section></main>;
 const isPopup=view==='popup'; return <main className={isPopup?'popup-shell':'panel-shell'}><Header compact={isPopup}/>{isPopup&&!result&&<><div className="page-context"><span className="eyebrow">CURRENT PAGE</span><strong>{location.hostname||'Ready to inspect'}</strong><span className="ready"><span className="pulse"/> Ready to analyze</span></div><button className="primary scan" onClick={run} disabled={loading}><ScanSearch size={17}/>{loading?'Analyzing…':'Scan this page'}</button><button className="demo-link" onClick={demo}><Sparkles size={14}/> Try demo mode</button><Footer/></>}{result&&<ResultView result={result} isPopup={isPopup} onScan={run} onDemo={demo} onShow={show} onOpen={openPanel} loading={loading} highlight={highlight} setHighlight={setHighlight}/>}</main>}
function ResultView({result,isPopup,onScan,onDemo,onShow,onOpen,loading,highlight,setHighlight}:{result:ScanResult;isPopup:boolean;onScan:()=>void;onDemo:()=>void;onShow:(d:Detection)=>void;onOpen:()=>void;loading:boolean;highlight:boolean;setHighlight:(v:boolean)=>void}){return <><div className="result-head"><div><div className="eyebrow">{result.isDemo?'DEMO ANALYSIS':'DARKLENS ANALYSIS'}</div><h1>{result.isDemo?'Synthetic patterns':'Manipulation risk'}</h1><p className="muted">{result.hostname}</p></div><div className={`score ${result.score>60?'high':''}`}><strong>{result.score}</strong><span>/ 100</span><small>{riskLabel(result.score)}</small></div></div><p className="disclaimer">Estimated score based on detected interface patterns. Not scientifically validated.</p><div className="result-meta"><b>{result.detections.length} potential patterns detected</b><label className="toggle-line"><input type="checkbox" checked={highlight} onChange={e=>setHighlight(e.target.checked)}/>{highlight?<Eye size={14}/>:<EyeOff size={14}/>} Highlights</label></div><div className="cards">{result.detections.length?result.detections.map(d=><Card key={d.id} d={d} onShow={isPopup?undefined:()=>onShow(d)}/>):<div className="empty"><Check size={24}/><b>No potential patterns detected</b><span>DarkLens found no strong evidence in the visible page content.</span></div>}</div><div className="actions">{isPopup&&<><button className="primary" onClick={onOpen}><ExternalLink size={15}/> Open full analysis</button><button className="secondary" onClick={onScan} disabled={loading}>{loading?'Scanning…':'Scan again'}</button></>}{!isPopup&&<button className="secondary" onClick={onDemo}>View demo examples</button>}</div>{isPopup&&<Footer/>}</>}
function Setting({title,desc,value,onChange}:{title:string;desc:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="setting"><div><b>{title}</b><span>{desc}</span></div><button className={`switch ${value?'on':''}`} aria-pressed={value} onClick={()=>onChange(!value)}><i/></button></div>}
function Footer(){return <footer><button onClick={()=>chrome.runtime.openOptionsPage()}><Settings size={13}/> Settings</button><span>Local-first analysis</span></footer>}
